### ISSUE TITLE
tvnamer always returns "No JSON object could be decoded"

### ISSUE THREAD

**Issue by mmbutter** [dbr/tvnamer#144]
I've tried installing with both pip and apt-get (after uninstalling the pip version) and every time I run tvnamer I get the error.

Full output:
```####################
# Starting tvnamer
# Found 1 episode
####################
# Processing file: NCIS.S08E01.HDTV.XviD-mOt.Pyramid.mkv
# Detected series: NCIS (season: 8, episode: 1)
Traceback (most recent call last):
  File "/usr/bin/tvnamer", line 4, in <module>
    main()
  File "/usr/share/tvnamer/main.py", line 418, in main
    tvnamer(paths = sorted(args))
  File "/usr/share/tvnamer/main.py", line 325, in tvnamer
    processFile(tvdb_instance, episode)
  File "/usr/share/tvnamer/main.py", line 170, in processFile
    episode.populateFromTvdb(tvdb_instance, force_name=Config['force_name'], series_id=Config['series_id'])
  File "/usr/share/tvnamer/utils.py", line 639, in populateFromTvdb
    show = tvdb_instance[force_name or self.seriesname]
  File "/usr/local/lib/python2.7/dist-packages/tvdb_api.py", line 1182, in __getitem__
    sid = self._nameToSid(key)
  File "/usr/local/lib/python2.7/dist-packages/tvdb_api.py", line 1163, in _nameToSid
    selected_series = self._getSeries(name)
  File "/usr/local/lib/python2.7/dist-packages/tvdb_api.py", line 963, in _getSeries
    allSeries = self.search(series)
  File "/usr/local/lib/python2.7/dist-packages/tvdb_api.py", line 943, in search
    seriesEt = self._getetsrc(self.config['url_getSeries'] % (series))
  File "/usr/local/lib/python2.7/dist-packages/tvdb_api.py", line 903, in _getetsrc
    src = self._loadUrl(url, language=language)
  File "/usr/local/lib/python2.7/dist-packages/tvdb_api.py", line 850, in _loadUrl
    self.authorize()
  File "/usr/local/lib/python2.7/dist-packages/tvdb_api.py", line 891, in authorize
    r_json = r.json()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by mmbutter** [comment]
I think I have this fixed. Looking around at other sources, I found these on a MythTV support forum and they seem to have fixed my problem.

```
sudo apt-get install python-pip
sudo pip install future requests_cache
sudo pip install --upgrade urllib3 requests
```
