### ISSUE TITLE
ValueError: unsupported pickle protocol: 3

### ISSUE THREAD

**Issue by lozbrown** [dbr/tvnamer#149]
I get the following error after pip upgrade to 2.5

`Loading config: /home/loz/.tvnamer.json
####################
# Starting tvnamer
# Found 4 episodes
Traceback (most recent call last):
  File "/usr/local/bin/tvnamer", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/tvnamer/main.py", line 449, in main
    tvnamer(paths = sorted(args))
  File "/usr/local/lib/python2.7/dist-packages/tvnamer/main.py", line 351, in tvnamer
    cache=cache,
  File "/usr/local/lib/python2.7/dist-packages/tvdb_api.py", line 726, in __init__
    self.session.remove_expired_responses()
  File "/usr/local/lib/python2.7/dist-packages/requests_cache/core.py", line 159, in remove_expired_responses
    self.cache.remove_old_entries(datetime.utcnow() - self._cache_expire_after)
  File "/usr/local/lib/python2.7/dist-packages/requests_cache/backends/base.py", line 110, in remove_old_entries
    response, created_at = self.responses[key]
  File "/usr/local/lib/python2.7/dist-packages/requests_cache/backends/storage/dbdict.py", line 163, in __getitem_
_
    return pickle.loads(bytes(super(DbPickleDict, self).__getitem__(key)))
ValueError: unsupported pickle protocol: 3`

**Comment by lozbrown** [comment]
This was resolved by setting the  for /usr/bin/python to point to pythin3.5 in my system, not sure why this application doesn't default to that
