### ISSUE TITLE
program is starting and giving a choice, but does not rename the file

### ISSUE THREAD

**Issue by huenchen** [dbr/tvnamer#157]
I have tvnamer installed on my Mac via Homebrew. After the update to Catalina it was still working. Just last night it startet to not rename the files. it is giving me a choice to choose from a list of shows, but afterwards it is just givin me the following error:

`Traceback (most recent call last):
  File "/usr/local/Cellar/tvnamer/2.5/libexec/bin/tvnamer", line 11, in <module>
    load_entry_point('tvnamer==2.5', 'console_scripts', 'tvnamer')()
  File "/usr/local/Cellar/tvnamer/2.5/libexec/lib/python3.7/site-packages/tvnamer/main.py", line 449, in main
    tvnamer(paths = sorted(args))
  File "/usr/local/Cellar/tvnamer/2.5/libexec/lib/python3.7/site-packages/tvnamer/main.py", line 355, in tvnamer
    processFile(tvdb_instance, episode)
  File "/usr/local/Cellar/tvnamer/2.5/libexec/lib/python3.7/site-packages/tvnamer/main.py", line 167, in processFile
    episode.populateFromTvdb(tvdb_instance, force_name=Config['force_name'], series_id=Config['series_id'])
  File "/usr/local/Cellar/tvnamer/2.5/libexec/lib/python3.7/site-packages/tvnamer/utils.py", line 641, in populateFromTvdb
    show = tvdb_instance[force_name or self.seriesname]
  File "/usr/local/Cellar/tvnamer/2.5/libexec/vendor/lib/python3.7/site-packages/tvdb_api.py", line 1182, in __getitem__
    sid = self._nameToSid(key)
  File "/usr/local/Cellar/tvnamer/2.5/libexec/vendor/lib/python3.7/site-packages/tvdb_api.py", line 1168, in _nameToSid
    self._getShowData(selected_series['id'], self.config['language'])
  File "/usr/local/Cellar/tvnamer/2.5/libexec/vendor/lib/python3.7/site-packages/tvdb_api.py", line 1092, in _getShowData
    for curInfo in seriesInfoEt.keys():
AttributeError: 'NoneType' object has no attribute 'keys'`
Unfortunately I do not know what is missing.

Thank you!

**Comment by ruuku** [comment]
This is an issue with thetvdb api (https://forums.thetvdb.com/viewtopic.php?f=122&t=60034)

Hopefully it will be fixed soon.

**Comment by huenchen** [comment]
thank you for the quick reply, so I will wait and hope!

**Comment by dbr** [comment]
Thanks for the information @ruuku !

I'll close this for now as it'll hopefully resolve itself on TheTVDB.com's side shortly
