### ISSUE TITLE
tvnamer not work

### ISSUE THREAD

**Issue by Monirzadeh** [dbr/tvnamer#158]
after run program get me a list of available option after i select get this error
i install from repository
```
Traceback (most recent call last):
  File "/usr/bin/tvnamer", line 6, in <module>
    tvnamer.main.main()
  File "/usr/share/tvnamer/main.py", line 449, in main
    tvnamer(paths = sorted(args))
  File "/usr/share/tvnamer/main.py", line 355, in tvnamer
    processFile(tvdb_instance, episode)
  File "/usr/share/tvnamer/main.py", line 167, in processFile
    episode.populateFromTvdb(tvdb_instance, force_name=Config['force_name'], series_id=Config['series_id'])
  File "/usr/share/tvnamer/utils.py", line 641, in populateFromTvdb
    show = tvdb_instance[force_name or self.seriesname]
  File "/home/me/.local/lib/python3.7/site-packages/tvdb_api.py", line 1182, in __getitem__
    sid = self._nameToSid(key)
  File "/home/me/.local/lib/python3.7/site-packages/tvdb_api.py", line 1168, in _nameToSid
    self._getShowData(selected_series['id'], self.config['language'])
  File "/home/me/.local/lib/python3.7/site-packages/tvdb_api.py", line 1092, in _getShowData
    for curInfo in seriesInfoEt.keys():
AttributeError: 'NoneType' object has no attribute 'keys'
```

**Comment by jonsag** [comment]
Same for me.
What thetvdb-API version is tvnamer using?
Seems they have launched API version 3 now.
v1 and v2 are shut down or...?

**Comment by dbr** [comment]
I believe this is the same issue as #157 - it's a temporary server error with TheTVDB, there is a forum thread about it:
https://forums.thetvdb.com/viewtopic.php?f=122&t=60034

I'll close this as it isn't anything tvnamer can do anything about (I should probably patch up the `tvdb_api` module to better handle this error as the NoneType error is not descriptive - but would still not work)
