### ISSUE TITLE
Stopped Working

### ISSUE THREAD

**Issue by bzh4bzh** [dbr/tvnamer#167]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/tvnamer", line 11, in <module>
    load_entry_point('tvnamer==2.5', 'console_scripts', 'tvnamer')()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tvnamer/main.py", line 449, in main
    tvnamer(paths = sorted(args))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tvnamer/main.py", line 355, in tvnamer
    processFile(tvdb_instance, episode)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tvnamer/main.py", line 167, in processFile
    episode.populateFromTvdb(tvdb_instance, force_name=Config['force_name'], series_id=Config['series_id'])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tvnamer/utils.py", line 641, in populateFromTvdb
    show = tvdb_instance[force_name or self.seriesname]
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tvdb_api.py", line 1182, in __getitem__
    sid = self._nameToSid(key)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tvdb_api.py", line 1163, in _nameToSid
    selected_series = self._getSeries(name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tvdb_api.py", line 963, in _getSeries
    allSeries = self.search(series)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tvdb_api.py", line 943, in search
    seriesEt = self._getetsrc(self.config['url_getSeries'] % (series))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tvdb_api.py", line 903, in _getetsrc
    src = self._loadUrl(url, language=language)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tvdb_api.py", line 850, in _loadUrl
    self.authorize()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tvdb_api.py", line 891, in authorize
    r_json = r.json()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by bzh4bzh** [comment]
Seemed like it was an issue with API temporarily not working.
