### ISSUE TITLE
Errors when running tvnamer after apt-get install

### ISSUE THREAD

**Issue by dinki** [dbr/tvnamer#204]
Hey guys.  Installed tvnamer using apt-get install tvnamer on my Open Media Vault Debian server.  I'm not sure where the problem lies as I'm not super technical.  Can someone look at my copy/paste and tell me where things are going wrong and wat I might do to correct it?

Thanks and all the best to you!

```
root@omv:/sharedfolders/downloads# ls COPS\ 2013-12-07\ Cops\ Blood\ and\ Scars\ Bro\ 2021-07-08-1730.mpg                             
COPS 2013-12-07 Cops Blood and Scars Bro 2021-07-08-1730.mpg                                                                          
root@omv:/sharedfolders/downloads# tvnamer COPS\ 2013-12-07\ Cops\ Blood\ and\ Scars\ Bro\ 2021-07-08-1730.mpg                        
####################                                                                                                                  
# Starting tvnamer                                                                                                                    
# Found 1 episode                                                                                                                     
####################                                                                                                                  
# Processing file: COPS 2013-12-07 Cops Blood and Scars Bro 2021-07-08-1730.mpg                                                       
# Detected series: COPS (episode: 2013-12-07)                                                                                         
Traceback (most recent call last):                                                                                                    
  File "/usr/bin/tvnamer", line 4, in <module>                                                                                        
    main()                                                                                                                            
  File "/usr/share/tvnamer/main.py", line 418, in main                                                                                
    tvnamer(paths = sorted(args))                                                                                                     
  File "/usr/share/tvnamer/main.py", line 325, in tvnamer                                                                             
    processFile(tvdb_instance, episode)                                                                                               
  File "/usr/share/tvnamer/main.py", line 170, in processFile                                                                         
    episode.populateFromTvdb(tvdb_instance, force_name=Config['force_name'], series_id=Config['series_id'])                           
  File "/usr/share/tvnamer/utils.py", line 639, in populateFromTvdb                                                                   
    show = tvdb_instance[force_name or self.seriesname]                                                                               
  File "/usr/lib/python2.7/dist-packages/tvdb_api.py", line 952, in __getitem__                                                       
    sid = self._nameToSid(key)                                                                                                        
  File "/usr/lib/python2.7/dist-packages/tvdb_api.py", line 932, in _nameToSid                                                        
    selected_series = self._getSeries( name )                                                                                         
  File "/usr/lib/python2.7/dist-packages/tvdb_api.py", line 718, in _getSeries                                                        
    allSeries = self.search(series)                                                                                                   
  File "/usr/lib/python2.7/dist-packages/tvdb_api.py", line 704, in search                                                            
    result['lid'] = self.config['langabbv_to_id'][result['language']]                                                                 
KeyError: 'all'     
```

**Comment by dbr** [comment]
From that error I suspect the version of the `tvdb_api` library installed is outdated, as that line of code is no longer present in the last few releases.

Possibly either:

1. The version of tvnamer in Debian packaged includes an overly old version of the `tvdb_api` dependency (which seems odd, as the tvnamer version is reasonably up-to-date)
2. You have an old version of `tvdb_api.py` installed somehow, and that is overriding the packaged version?

**Comment by dinki** [comment]
Thanks for the tips.  I stop using this last year so I'll just close this ticket.
